# Generated by Django 2.2.5 on 2021-11-16 01:40

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211112_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog2',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='blog2',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='create_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
    ]
