# Generated by Django 2.2.5 on 2021-11-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211116_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog2',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
