# Generated by Django 2.2.5 on 2021-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211116_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog2',
            name='user_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
