# Generated by Django 2.2.5 on 2021-11-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211116_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog2',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='blog2',
            name='user_name',
        ),
    ]
