# Generated by Django 2.2.5 on 2021-11-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211116_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog2',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blog2',
            name='user_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
