# Generated by Django 2.2.5 on 2021-11-16 01:52

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211116_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog2',
            name='update_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
    ]
