# Generated by Django 2.2.5 on 2021-11-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211116_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog2',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
